{% set name = "castorapi" %}
{% set version = "0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f9172707bd53bac3a84bf38f801541f7096fd5b1122883ab068c2093259cc04a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - json5
    - pandas
    - pip
    - progressbar2
    - python
    - requests
  run:
    - json5
    - pandas
    - progressbar2
    - python
    - requests

test:
  imports:
    - castorapi

about:
  home: https://github.com/wouterpotters/castorapi
  summary: Python API wrapper for Castor EDC to fetch data from your clinical study.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/wouterpotters/castorapi#usage
  dev_url: https://github.com/wouterpotters/castorapi
  description: castorapi is a python API wrapper for the Castor EDC API. The author is not affiliated with Castor EDC. Use at your own risk.

extra:
  recipe-maintainers:
    - wouterpotters
